import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle,AiFillLinkedin,AiFillYoutube} from 'react-icons/ai'
import Image from 'next/image'
import deved from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'
import Link from 'next/link'


export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Andrew Portfolio Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg-px-40 dark:bg-gray-900 ">
        <section className="bg-blend-hue min-h-screen "> 
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-burtons dark:text-white">//:NDREW</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)}className="cursor-pointer"/>
              </li>
              <li><a className="bg-gradient-to-r from-teal-200 to-lime-200 hover:bg-gradient-to-l hover:from-teal-200 hover:to-lime-200 focus:ring-4 focus:outline-none focus:ring-lime-200 dark:focus:ring-teal-700 font-medium rounded-lg text-sm px-5 text-center mr-2 mb-2 text-white py-2  ml-8" href="#">Resume</a></li>
              
            </ul>
          </nav>

          <div className="text-center p-10" >
            <h2 className="text-5xl py-2 text-teal-500 font-medium md:text-6xl">Andrew Adhikari</h2>
            <h3 className="text-2xl py-2 md:text-3xl dark:text-white">Developer and Designer</h3>
            <p className="text-md py-5 leading-8 text-grey-800 md:text-xl max-w-xl mx-auto dark:text-white">Lorem ipsum, dolor sit amet consectetur adipisicing elit. At perspiciatis cum eum aliquid nam, aliquam illo in voluptas itaque fugit fuga? In numquam eius illum? Voluptatibus assumenda iusto error nesciunt.</p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-grey-600">
            <AiFillTwitterCircle/>
            <AiFillLinkedin/>
            <AiFillYoutube/>
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:h-96 md:w-96">
            <Image src={deved} layout="fill" objectFit="cover"></Image>

          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 text-center">Services I offer</h3>
            <p className="text-md py-2 leading-8 tet-grey-800 text-center">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Architecto nemo, amet <span className="text-teal-500">agencies consulted for</span> quam id vero ratione recusandae earum. Sint voluptate vitae excepturi, officia, <span className="text-teal-500">maximize</span> maxime maiores ipsa delectus esse ipsam quos id?
            </p>
            <p className='text-md py2 leading-8 text-grey-800 text-center'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Alias harum obcaecati vel? Quos, aliquid officia labore excepturi fuga sunt aut accusantium. Blanditiis eum modi possimus ad mollitia. Voluptates, placeat consequuntur.</p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={design} width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2' >Beautiful Designs <span className="bg-pink-100 text-pink-800 text-sm font-medium mr-2 px-2.5 py-0.5 rounded dark:bg-pink-200 dark:text-pink-900">Hello World Tag</span></h3>
              <p className='py-2'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id, eligendi vero. Corporis autem dicta at. Alias minus placeat beatae sapiente dolore molestiae non distinctio inventore animi aliquam? Quam, doloribus molestiae?</p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='text-grey-800 py-1'>Photoshop</p>
              <p className='text-grey-800 py-1'>FIGMA</p>
              <p className='text-grey-800 py-1'>TEST</p>
              <p className='text-grey-800 py-1'>123PIX</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id, eligendi vero. Corporis autem dicta at. Alias minus placeat beatae sapiente dolore molestiae non distinctio inventore animi aliquam? Quam, doloribus molestiae?</p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='text-grey-800 py-1'>Photoshop</p>
              <p className='text-grey-800 py-1'>FIGMA</p>
              <p className='text-grey-800 py-1'>TEST</p>
              <p className='text-grey-800 py-1'>123PIX</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image src={consulting} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautiful Designs</h3>
              <p className='py-2'>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id, eligendi vero. Corporis autem dicta at. Alias minus placeat beatae sapiente dolore molestiae non distinctio inventore animi aliquam? Quam, doloribus molestiae?</p>
              <h4 className='py-4 text-teal-600'>Design tools i use</h4>
              <p className='text-grey-800 py-1'>Photoshop</p>
              <p className='text-grey-800 py-1'>FIGMA</p>
              <p className='text-grey-800 py-1'>TEST</p>
              <p className='text-grey-800 py-1'>123PIX</p>
            </div>
          </div>
        </section>
        <section>
          <div>
          <h3 className='text-3xl py-1 text-center'>Portfolio World</h3>
          <p className="text-md py-2 leading-8 tet-grey-800 text-center">
              Lorem ipsum dolor, sit amet consectetur adipisicing elit. Architecto nemo, amet <span className="text-teal-500">agencies consulted for</span> quam id vero ratione recusandae earum. Sint voluptate vitae excepturi, officia, <span className="text-teal-500">maximize</span> maxime maiores ipsa delectus esse ipsam quos id?
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className="basis-1/3 flex-1"><Image src={web1} className='rounded-log object-cover' width={'100%'} height={'100%'} layout='responsive' /></div>
            <div className="basis-1/3 flex-1"><Image src={web2} className='rounded-log object-cover' width={'100%'} height={'100%'} layout='responsive' /></div>
            <div className="basis-1/3 flex-1"><Image src={web3} className='rounded-log object-cover' width={'100%'} height={'100%'} layout='responsive' /></div>
            <div className="basis-1/3 flex-1"><Image src={web4} className='rounded-log object-cover' width={'100%'} height={'100%'} layout='responsive' /></div>
            <div className="basis-1/3 flex-1"><Image src={web5} className='rounded-log object-cover' width={'100%'} height={'100%'} layout='responsive' /></div>
            <div className="basis-1/3 flex-1"><Image src={web6} className='rounded-log object-cover' width={'100%'} height={'100%'} layout='responsive' /></div>

            
          </div>    
        </section>

        <section>

        <div className='lg:flex gap-10'>
        <div class="bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700  text-center p-10 my-10">
        <a href="#"><Image src={code}/></a>
        <div class="p-5"><a href="#"><h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5></a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
        <a href="#" class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Read more <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </a>
        </div>
        </div>
        <div class="bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700  text-center p-10 my-10">
        <a href="#"><Image src={code}/></a>
        <div class="p-5"><a href="#"><h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5></a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
        <a href="#" class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Read more <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </a>
        </div>
        </div>
        <div class="bg-white rounded-lg border border-gray-200 shadow-md dark:bg-gray-800 dark:border-gray-700 text-center p-10 my-10">
        <a href="#"><Image src={code}/></a>
        <div class="p-5"><a href="#"><h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 dark:text-white">Noteworthy technology acquisitions 2021</h5></a>
        <p class="mb-3 font-normal text-gray-700 dark:text-gray-400">Here are the biggest enterprise technology acquisitions of 2021 so far, in reverse chronological order.</p>
        <a href="#" class="inline-flex items-center py-2 px-3 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Read more <svg aria-hidden="true" class="ml-2 -mr-1 w-4 h-4" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 3.293a1 1 0 011.414 0l6 6a1 1 0 010 1.414l-6 6a1 1 0 01-1.414-1.414L14.586 11H3a1 1 0 110-2h11.586l-4.293-4.293a1 1 0 010-1.414z" clip-rule="evenodd"></path></svg>
        </a>
        </div>
        </div>
        </div>
          
        

        </section>
        
        <footer class="p-4 bg-white rounded-lg md:flex md:items-center md:justify-between md:p-6 dark:bg-gray-800">
        <span class="text-sm text-gray-500 sm:text-center dark:text-gray-400">© 2022 <a href="https://andrewadhikari.com"      class="hover:underline">Andrew Adhikari</a>. All Rights Reserved.
        </span>
        <ul class="flex flex-wrap items-center mt-3 text-sm text-gray-500 dark:text-gray-400 sm:mt-0">
        <li><a href="/about" class="mr-4 hover:underline md:mr-6 ">About</a></li>
        <li><a href="#" class="mr-4 hover:underline md:mr-6">Privacy Policy</a></li>
        <li> <a href="#" class="mr-4 hover:underline md:mr-6">Licensing</a></li>
        <li><a href="#" class="hover:underline">Contact</a></li>
        </ul>
        </footer>
      </main>

    </div>
  )
}
